language: python
python:
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y openssl

install:
  - pip install -r requirements.txt

script:
  - python main.py
