language: python
python:
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y openssl

install:
  - pip install -r requirements.txt
  - pip uninstall urllib3
  - pip install urllib3==1.26.6

script:
  - python main.py
